server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: 
      - prometheus.club012.com

# Windows에서는 htstRootfs를 false로
# nodeExporter:
#   hostRootfs: false
# extraScrapeConfigs: |
#   - job_name: "mongodb-exporter"
#     static_configs:
#       - targets:
#           - kpcard-mongodb-metrics.mongodb-cluster.svc.cluster.local:9216

networkPolicy:
  ## Enable creation of NetworkPolicy resources.
  ##
  enabled: true
