controller:
  replicaCount: 2
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
  metrics:
    enabled: true
    # serviceMonitor로 대체
    # service:
    #   annotations:
    #     prometheus.io/scrape: "true"
    #     prometheus.io/port: "10254"
    serviceMonitor:
      enabled: true
  admissionWebhooks:
    certManager:
      enabled: "true"
