controller:
  replicaCount: 2
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  admissionWebhooks:
    certManager:
      enabled: "true"
