# https://github.com/apache/skywalking/blob/master/docker/docker-compose.yml
version: '3.8'
services:
  oap:
    image: apache/skywalking-oap-server:9.2.0
    container_name: oap
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms2048m -Xmx2048m"
    networks:
      - skywalking

  oap-ui:
    image: apache/skywalking-ui:9.2.0
    container_name: oap-ui
    depends_on:
      oap:
        condition: service_healthy
    links:
      - oap
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
    networks:
      - skywalking

networks:
  skywalking:
    external: true
