configs:
  params:
    server.insecur: true
  cm:
    accounts.devuser: apiKey, login
  rbac:
    policy.csv: |
      p, role:devuser, applications, *, */*, allow
      p, role:devuser, clusters, get, *, allow
      p, role:devuser, projects, get, *, allow
      p, role:devuser, repositories, get, *, allow
      p, role:devuser, repositories, create, *, allow
      p, role:devuser, repositories, update, *, allow
      p, role:devuser, repositories, delete, *, allow
      g, devuser, role:devuser
