# Deployment nginx
# kubectl apply -f nginx-deploy-svc.yaml
# kubectl get pods -l run=nginx-image -o wide
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kpcard-development
  name: nginx-image
spec:
  selector:
    matchLabels:
      run: nginx-image
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx-image
    spec:
      containers:
      - name: nginx-image
        image: docker.kpcard.co.kr/nginx:1.21.5
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "10m"
          requests:
            memory: "32Mi"
            cpu: "5m"
---
# Expose nginx service
# kubectl expose deployment/my-nginx 또는
# kubectl apply -f nginx-svc.yaml
# kubectl get svc my-nginx
# kubectl describe svc my-nginx
apiVersion: v1
kind: Service
metadata:
  namespace: kpcard-development
  name: nginx-image
  labels:
    run: nginx-image
spec:
  type: ClusterIP # default type
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-image