kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-role
rules:
- apiGroups:
  - '*'
  resources:
  - 'namespaces'
  - 'pods'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloak-role
subjects:
- kind: Group
  name: k8s-role
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: ldap-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: k8s-admin-role
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: ldap-admin-role
  apiGroup: rbac.authorization.k8s.io
