image:
  tag: 5.0.13-debian-11-r12
architecture: replicaset
replicaCount: 3
auth:
  enabled: true
  rootUser: kpcadmin
  rootPassword: kpcard
replicaSetName: MainRepSet
# livenessProbe:
#   enabled: false
# readinessProbe:
#   enabled: false
arbiter:
  enabled: false
externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts:
      - 32017
      - 32018
      - 32019
    domain: docker-desktop
metrics:
  enabled: true
