fullnameOverride: "mongodb"
image:
  tag: 5.0.13-debian-11-r12
architecture: replicaset
replicaCount: 3
auth:
  enabled: true
  rootUser: kpcadmin
  rootPassword: kpcard1@
replicaSetName: MainRepSet
# 동시에 파드 생성(기본값은 OrderedReady)
# podManagementPolicy: Parallel
#
# Disable Liveness Probe(기본값은 true)
# livenessProbe:
#   enabled: false
# Disable Readiness Probe(기본값은 true)
readinessProbe:
  enabled: false
arbiter:
  enabled: false
# externalAccess:
#   enabled: true
#   service:
#     type: NodePort
#     nodePorts:
#       - 32017
#       - 32018
#       - 32019
#     domain: docker-desktop
metrics:
  enabled: true
