apiVersion: v1
kind: Pod
metadata:
  name: secret-1401
  namespace: admin1401
spec:
  containers:
    - name: secret-admin
      image: busybox
      command: ["sh", "-c", "sleep", "4800"]
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret-volume"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
---
# kubectl run secret-1401 -n admin1401 --image=busybox --dry-run=client -o yaml --command sleep 4800 > pod.yaml
# edit pod.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-1401
  name: secret-1401
  namespace: admin1401
spec:
  containers:
    - command:
        - sleep
        - "4800"
      image: busybox
      name: secret-admin
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret-volume"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret

$ kubectl apply -f pod.yaml