# kubectl -n mongodb apply -f mongodb-statefulset.yaml
# kubectl -n mongodb delete -f mongodb-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  # namespace: mongodb
spec:
  serviceName: mongodb
  selector:
    matchLabels:
      app: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo
          command: # <- mongo "init" command>
          - mongod
          - "--bind_ip"
          - "0.0.0.0"
          - "--replSet"
          - "MainRepSet"
          ports: 
            - containerPort: 27017
              name: "mongodb"
          volumeMounts:
            - name: data
              mountPath: /data/db
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 1Gi
