# create PersistentVolme(mongodb-pv$)
# kubectl apply -f pv.yaml
# kubectl get pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv1
spec:
  storageClassName: mongodb-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/mongodb/data1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv2
spec:
  storageClassName: mongodb-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/mongodb/data2"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv3
spec:
  storageClassName: mongodb-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/mongodb/data3"
