# create PersistentVolme(mysql-pv$)
# kubectl apply -f pv.yaml
# kubectl get pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/mysql/data1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/mysql/data2"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv3
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/mysql/data3"
