usePassword: false
image:
  tag: 7.0.5
cluster:
  nodes: 6
  replicas: 1
service:
  type: NodePort
  ports:
    redis: 6379
  # port range(30000~32767)
  nodePorts:
    redis: 32379
metrics:
  enabled: true
