fullnameOverride: "redis"
image:
  tag: 7.4.3
auth:
  password: a-very-complex-password-here
master:
  count: 1
  # resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 256Mi
  #   requests: 
  #     cpu: 50m
  #     memory: 10Mi
replica:
  replicaCount: 3
  # resources:
    # limits:
    #   cpu: 1000m
    #   memory: 256Mi
    # requests: 
    #   cpu: 50m
    #   memory: 10Mi
sentinel:
  enabled: true
  image:
    tag: 7.4.3
  masterSet: sentinel-master

## Prometheus Exporter / Metrics
##
metrics:
  ## @param metrics.enabled Start a side-car prometheus exporter
  ##
  enabled: true
  ## Enable this if you're using https://github.com/coreos/prometheus-operator
  ##
  serviceMonitor:
    ## @param metrics.serviceMonitor.enabled If `true`, creates a Prometheus Operator ServiceMonitor (also requires `metrics.enabled` to be `true`)
    ##
    enabled: true
 