version: "3"
services:
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:7.17.6
    container_name: elastic-agent
    volumes:
      - ${PWD}/certs:/usr/share/elastic-agent/certs
    ports:
      - 8220:8220
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - ELASTICSEARCH_HOST=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=np0lB2RBCijOZb1bEOiL
      - ELASTICSEARCH_CA=/usr/share/elastic-agent/certs/ca.crt
      - FLEET_SERVER_ENABLE=1
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NzEwMTMzNzIwMzU6T082a1QxTjJULUd0dkhSaHNDM1RHdw
      - FLEET_SERVER_HOST=fleet-server
      - FLEET_SERVER_PORT=8220
      - FLEET_SERVER_INSECURE_HTTP=true
    networks:
      - elastic

networks:
  elastic:
    external: true
