# AWX deploy
# kubectl apply -f awx-tower.yml -n awx
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-tower
spec:
  # service_type: nodeport
  ingress_type: ingress
  ingress_hosts:
    - hostname: awx.club012.com
      tls_secret: awx-tls
  ingress_controller: traefik
  ingress_annotations: | 
    cert-manager.io/cluster-issuer: letsencrypt-staging
  projects_persistence: true
  projects_storage_size: 20Gi
  projects_storage_access_mode: ReadWriteOnce
  extra_settings:
    - setting: CSRF_TRUSTED_ORIGINS
      value:
        - https://awx.club012.com
#  web_resource_requirements:
#    requests:
#      cpu: 200m
#      memory: 1Gi
#    limits:
#      cpu: 1000m
#      memor: 2Gi
