global:
  ldapDomain: "kpcard.co.kr"
  # adminUser: "ldapadmin"
  adminPassword: "kpcard1@"
  # configUserEnabled: false
  # configUser: "ldapadmin"
  # configPassword: "kpcard1@"

replicaCount: 1

# users: kpcadmin,deploy
# userPasswords: kpcard1@,kpcard
# group: admin

## Replication
replication:
  enabled: false

phpldapadmin:
  enabled: true
  ingress:
    enabled: true
    annotations: {}
    # Assuming that ingress-nginx is used
    ingressClassName: nginx
    path: /
    ## Ingress Host
    hosts:
    - pla.club012.com
  env:
    PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
ltb-passwd:
  enabled : true
  ingress:
    enabled: true
    annotations: {}
    # Assuming that ingress-nginx is used
    ingressClassName: nginx
    hosts:
    - ltb.club012.com
