# kubectl apply -n argucd -f mysql-root-secret.yaml
# echo 'root' | base64
# echo '%' | base64
# echo 'kpcard1@' | base64
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-secret
type: Opaque
data:
  rootUser: cm9vdA==
  rootHost: JQ==
  rootPassword: a3BjYXJkMUA=
