apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  log.level: info
  registries.conf: |
    registries:
    - name: KPC Registry
      prefix: docker.kpcard.co.kr
      api_url: https://docker.kpcard.co.kr
      credentials: pullsecret:argocd/kpcard-registry-cred
      insecure: true
      default: true