# helm chart values for rabbitmq
persistence:
  enabled: true
  #   # storageClass: nfs-client
  #   storageClass: local-path
  size: 500Mi
nameOverride: cluster
replicaCount: 3
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: "mq-admin.k8s.local"
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 1Gi
# Additional plugins
communityPlugins: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.10.2/rabbitmq_delayed_message_exchange-3.10.2.ez"
extraPlugins: "rabbitmq_delayed_message_exchange"
