# helm chart values for rabbitmq
# persistence:
#   enabled: true
#   # storageClass: nfs-client
#   storageClass: local-path
#   size: 500Mi
nameOverride: cluster
namespaceOverride: rabbitmq-system
replicaCount: 3
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: "mq-admin.k8s.local"
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 1Gi
