apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-cred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJkb2NrZXIuY2x1YjAxMi5jb20iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJjaHJpcyIsCiAgICAgICJwYXNzd29yZCI6ICJsZGFwNDhAJiIsCiAgICAgICJhdXRoIjogIlkyaHlhWE02YkdSaGNEUTRRQ1k9IgogICAgfQogIH0KfQo=