# kubectl apply -n playground -f redis-service-playground.yaml
kind: Service
apiVersion: v1
metadata:
  name: redis
  # namespace: playground
spec:
  type: ExternalName
  externalName: redis.redis.svc.cluster.local
  ports:
  - port: 6379